# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0002_auto_20170503_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='pause_after',
            field=models.PositiveIntegerField(default=0, help_text='In seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='count',
            field=models.PositiveIntegerField(help_text='In units for this food_type'),
        ),
    ]
