# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0003_auto_20170503_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
