# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0004_refrigerator_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='refrigerator',
            field=models.ForeignKey(help_text='Refrigerator stored this food item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refrigerator.Refrigerator'),
        ),
    ]
