# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0005_auto_20170504_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='image_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
